<div class="consulta-container">                                                                                                                                                                                                                                                      
    <div class="consulta">                                                                                                                                                                                                                                                            
        <div class="form-group">                                                                                                                                                                                                                                                      
            <label for="consulta-descricao">@{{ $ctrl.label.length > 0 ? $ctrl.label + ':' : '' }}</label>                                                                                                                                                                         
            <div class="input-group  ">                                                                                                                                                                                                                                               
                <input type="search" ng-model="$ctrl.SEARCH_RESULT" ng-keydown="$ctrl.showModal($event)" name="consulta_descricao" class="form-control consulta-descricao input-medio objConsulta" autocomplete="off" @{{ $ctrl.required == true ? 'required' : '' }} value="" readonly>                                                                        
                <button type="button" class="input-group-addon btn-filtro btn-filtro-consulta search-button " tabindex="-1"><span class="fa fa-search"></span></button>                                                                                                               
                <button type="button" class="input-group-addon btn-filtro btn-apagar-filtro btn-apagar-filtro-consulta search-button " tabindex="-1"><span class="fa fa-close"></span></button>                                                                                       
            </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
            <div class="_consulta_imputs">                                                                                                                                                                                                                                            
                <input type="hidden" name="_agrupamento_id" class="_consulta_imputs _agrupamento_id ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty" objcampo="ID" value="" ng-model="vm.filtro.agrupamento_id" ng-update-hidden="">                                      
                <input type="hidden" name="_agrupamento_descricao" class="_consulta_imputs _agrupamento_descricao ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty" objcampo="DESCRICAO" value="" ng-model="vm.filtro.agrupamento_descricao" ng-update-hidden="">          
                <input type="hidden" name="_pedido_perfil" class="_consulta_imputs _pedido_perfil ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty" objcampo="PERFIL" value="" ng-model="vm.filtro.pedido_perfil" ng-update-hidden="">                                     
                <input type="hidden" name="" class="_consulta_imputs  _todos_selecionado" value="0">                                                                                                                                                                                  
            </div>                                                                                                                                                                                                                                                                    
            <div class="_consulta_parametros">                                                                                                                                                                                                                                        
                <input type="hidden" class="_valida_fechar_lista" value="0">                                                                                                                                                                                                          
                <input type="hidden" name=" " class="_consulta_imputs  _todos_selecionar" objcampo="noclear" value="0">
                <input type="hidden" class="_valor_selecionado_consulta">
            </div>                                                                                                                                                                                                                                                                    
        </div>                                                                                                                                                                                                                                                                        
    </div>                                                                                                                                                                                                                                                                            
</div>                     

@include('helper.include.view.gc-search-modal')