		.copy('node_modules/bootstrap-sass/assets/fonts', 'public/build/assets/fonts')
		.copy('resources/assets/fonts', 'public/build/assets/fonts')		
		.copy('resources/assets/js/helper/plugin/jquery.shCircleLoader.js', jsPathPublic)
		.copy('resources/assets/js/helper/plugin/jquery.shCircleLoader-min.js', jsPathPublic)
		.copy('resources/assets/js/helper/plugin/jquery-ui.min.js', jsPathPublic)
		.copy('resources/assets/js/helper/plugin/jquery.ui.touch-punch.min.js', jsPathPublic)
		.copy('resources/assets/js/helper/plugin/jquery-dateFormat.min.js', jsPathPublic)
		.copy('resources/assets/sass/helper/nvd3.scss', cssPathPublic)